reel_miami/main/routes.py
from datetime import date, timedelta

import dateutil
from flask import Blueprint, current_app, flash, redirect, render_template, \
    request, url_for

from ..feeds import agile, cosford, mbc, tower
from reel_miami.models import Venue

main = Blueprint('main', __name__)


@main.context_processor
def context_processor():
    """Add the current day to all templates.

    Used for the datepicker at the top of the index page. Python's timedelta
    is also passed to the processor so the subsequent dates can be added to the
    datepicker buttons.
    """
    today = date.today()

    return {'today': today, 'timedelta': timedelta}


@main.route('/', methods=['GET', 'POST'])
@main.route('/home', methods=['GET', 'POST'])
def index():
    """Render the index/home page.

    All venue feeds are called in order to render the template with data.
    """
    if request.method == 'POST':
        date_to_seek = dateutil.parser.parse(request.form['date'])
    else:
        date_to_seek = date.today()

    cgac_films = agile.AgileEvent.fetch_agile_events(current_app.config['CGAC_GUID'],
                                                     date_to_seek)
    omb_films = agile.AgileEvent.fetch_agile_events(current_app.config['OMB_GUID'],
                                                    date_to_seek)

    cosford_films = cosford.fetch_cosford_events(date_to_seek)
    mbc_films = mbc.MBCEvent.fetch_mbc_events(date_to_seek)
    tower_films = tower.fetch_tower_events(date_to_seek)

    return render_template('index.html', title='Home',
                           cgac_films=cgac_films,
                           omb_films=omb_films,
                           mbc_films=mbc_films,
                           tower_films=tower_films,
                           cosford_films=cosford_films)


@main.route('/about')
def about():
    """Render the about page."""
    return render_template('about.html', title='About')


@main.route('/venues')
def venues():
    """Render the venue directory page."""
    venues = Venue.query.order_by(Venue.name).all()

    if not venues:
        flash('No venues found.', 'warning')
        return redirect(url_for('main.index'))

    return render_template('venue-directory.html', title='Venues',
                           venues=venues)


@main.route('/venue/<int:id>')
def venue(id):
    """Render the page for a venue."""
    venue = Venue.query.filter_by(id=id).first_or_404()

    if not venue:
        flash('No venue found.', 'warning')
        return redirect(url_for('main.venues'))

    venue_photo = url_for('static',
                          filename=f'img/venues/{venue.venue_photo}')

    return render_template('venue-listing.html', venue=venue,
                           venue_photo=venue_photo, title=venue.name)


@main.route('/admin')
def admin():
    """Redirect to the Flask-Admin index page."""
    return redirect(url_for('main.admin'))

reel_miami/templates/about.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<article class="about">
  <p>The mission of Reel Miami is to promote film culture in Miami-Dade County.
     It is born out of a lack of a centralized resource for art house film in the region.</p>
  <p>The website achieves this mission primarily by listing all specialty film screenings located
     throughout Greater Miami.</p>
  <p>In keeping with the spirit of the non-profit art house, this website is
     entirely open source. The code can be reviewed <a href="https://github.com/deadlyraptor/reel-miami">here</a>.</p>
</article>
{% endblock content %}

reel_miami/templates/admin_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated %}
<div class="navbar-text btn-group pull-right">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        <i class="glyphicon glyphicon-user"></i>
        {% if current_user.first_name -%}
          {{ current_user.first_name }}
        {% else -%}
          {{ current_user.email }}
        {%- endif %}<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
        <li><a href="{{ url_for('security.logout') }}">Log out</a></li>
    </ul>
</div>
{% endif %}
{% endblock access_control %}

reel_miami/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/styles.css') }}" />

  {% if title %}
  <title>{{ title }} | Reel Miami</title>
  {% else %}
  <title>Reel Miami</title>
  {% endif %}
</head>

<body>
  <!-- Start Navbar -->
  {% include 'nav.html' %}
  <!-- End Navbar -->

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      <ul class="flashes">
        {% for category, message in messages %}
          <li class="{{ category }}">{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}

{% block content%}{% endblock content %}

<!-- Start Footer -->
{% include 'footer.html' %}
<!-- End Footer -->

</body>

</html>

reel_miami/templates/footer.html
<footer class="footer-nav">
  <div class="author">
    Developed by <a href="https://github.com/deadlyraptor">Javier Chavez</a>
  </div>
  <ul class="footer-menu">
    <li><a href="{{ url_for('main.index') }}">Home</a></li>
    <li><a href="{{ url_for('main.venues') }}">Venues</a></li>
    <li><a href="{{ url_for('main.about') }}">About</a></li>
    <li><a href="{{ url_for('main.admin') }}">Admin</a></li>
  </ul>
</footer>

reel_miami/templates/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
{% include "snippets/date-picker-snippet.html" %}
<div class="venues-container">
  <!-- Coral Gables Art Cinema -->
  <div class="venue-container">
    <div class="venue-name">
      <h3><a href="http://gablescinema.com">Coral Gables Art Cinema</a></h3>
    </div>
    {% if cgac_films %}
      {% for film in cgac_films %}
        {% include "snippets/film-snippet.html" %}
      {% endfor %}
    {% else %}
      {% include "snippets/no-films-snippet.html" %}
    {% endif %}
  </div>
  <!-- O Cinema Miami Beach -->
  <div class="venue-container">
    <div class="venue-name">
      <h3><a href="https://www.o-cinema.org/">O Cinema Miami Beach</a></h3>
    </div>
    {% if omb_films %}
      {% for film in omb_films %}
        {% include "snippets/film-snippet.html" %}
      {% endfor %}
    {% else %}
      {% include "snippets/no-films-snippet.html" %}
    {% endif %}
  </div>
  <!-- Miami Beach Cinematheque -->
  <div class="venue-container">
    <div class="venue-name">
      <h3><a href="http://mbcinema.com/">Miami Beach Cinematheque</a></h3>
    </div>
    {% if mbc_films %}
      {% for film in mbc_films %}
        {% include "snippets/film-snippet.html" %}
      {% endfor %}
    {% else %}
      {% include "snippets/no-films-snippet.html" %}
    {% endif %}
  </div>
  <!-- Tower Theater Miami -->
  <div class="venue-container">
    <div class="venue-name">
      <h3><a href="https://towertheatermiami.com">Tower Theater Miami</a></h3>
    </div>
    {% if tower_films %}
      {% for film in tower_films %}
        {% include "snippets/film-snippet.html" %}
      {% endfor %}
    {% else %}
      {% include "snippets/no-films-snippet.html" %}
    {% endif %}
  </div>
  <!-- Cosford Cinema -->
  <div class="venue-container">
    <div class="venue-name">
      <h3><a href="http://www.cosfordcinema.com/">Cosford Cinema</a></h3>
    </div>
    {% if cosford_films %}
      {% for film in cosford_films %}
        {% include "snippets/film-snippet.html" %}
      {% endfor %}
    {% else %}
      {% include "snippets/no-films-snippet.html" %}
    {% endif %}
  </div>
</div>
{% endblock content %}

reel_miami/templates/my_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated %}
<div class="navbar-text btn-group pull-right">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        <i class="glyphicon glyphicon-user"></i>
        {% if current_user.first_name -%}
          {{ current_user.first_name }}
        {% else -%}
          {{ current_user.email }}
        {%- endif %}<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
        <li><a href="{{ url_for('security.logout') }}">Log out</a></li>
    </ul>
</div>
{% endif %}
{% endblock access_control %}

reel_miami/templates/nav.html
<nav class="main-nav">
  <div class="logo">
    <a href="{{ url_for('main.index') }}">Reel Miami</a>
  </div>
  <ul class="menu">
    <li><a href="{{ url_for('main.index') }}">Home</a></li>
    <li><a href="{{ url_for('main.venues') }}">Venues</a></li>
    <li><a href="{{ url_for('main.about') }}">About</a></li>
  </ul>
</nav>

reel_miami/templates/venue-directory.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<div class="venue-grid">
  {% for venue in venues %}
    <div class="venue-grid-item">
      <a href="{{ url_for('main.venue', id=venue.id) }}"><img src="static/img/venues/{{ venue.venue_photo }}" height="175" width="350" /></a>
      <a href="{{ url_for('main.venue', id=venue.id) }}"><p>{{ venue.name }}</p></a>
    </div>
  {% endfor %}
</div>
{% endblock content %}

reel_miami/templates/venue-listing.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<div class="venue-listing">
  <div class="venue-photo">
    <img src="{{ venue_photo }}" height="350" width="500" class="photo"/>
  </div>
  <div class="venue-info">
    <p>{{ venue.name }}</p>
    <p>{{ venue.address1 }}
      {% if venue.address2 %}
        {{ venue.address2 }}
      {% endif %}<br />
      {{ venue.city }}, {{ venue.state }} {{ venue.postal_code }}
    </p>
    <p>{{ venue.phone_number }}</p>
    <p><a href="{{ venue.web_url }}">{{ venue.web_url }}</a></p>
    <p>{{ venue.description }}</p>
  </div>
</div>
{% endblock content %}